version: '3'
services:

  reverse_proxy:
    restart: always
    image: nginx:1.19.0-alpine
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./src/static:/static
    ports:
    - "80:80"
    networks:
      - front-net

  bank_api:
    build: .
    expose:
    - "5000"
    depends_on:
      - bank_db
    volumes:
      - ./src:/sourcecode
    networks:
      - back-net
      - front-net

  bank_db:
    image: postgres:9.6-alpine
    restart: always
    ports:
      - "5432:5432"
    networks:
      - back-net
    environment:
      - POSTGRES_PASSWORD=testing

networks:
  back-net:
  front-net:

volumes:
  conf:
  static: