version: '3'
services:

  reverse-proxy:
    restart: always
    image: nginx:1.19.0-alpine
    volumes:
    - ./conf:/etc/nginx/conf.d
    - ./static:/static
    links:
    - api:api
    ports:
    - "80:80"

  bank-api:
    build: .
    expose:
    - "5000"
    command: gunicorn simplebanking.wsgi -b 0.0.0.0:5000 --log-level=debug --log-file=-
    depends_on:
      - primary_db
    volumes:
      - .:/sourcecode

  primary_db:
    image: postgres:9.6
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/9.6

volumes:
  pgdata:
  conf:
  static: