# Generated by Django 2.1.3 on 2018-12-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
